pipeline {
  agent any
  stages {
    stage('clean') {
      steps{
        sh "mvn clean"
      }
    }
    stage('Build'){
      steps{
        sh "sudo mvn install -DskipTests=true"
      }
    }
  }
}
